version: '3'

env:
  PYENV_VERSION: 3.12

tasks:
  init:
    desc: Init for local dev
    cmds:
      # - rm -rf .venv
      - python --version && python -m venv .venv
      - .venv/bin/pip install --upgrade pip wheel
      - .venv/bin/pip install -r requirements.txt
      - gcloud init

  auth:
    desc: Authenticate Google Cloud SDK
    cmds:
      - gcloud auth application-default login

  download-source:
    desc: Download data from sources
    cmds:
      - .venv/bin/python data-source-ingester/download_files.py

  load-bq:
    desc: Load source data into Google BigQuery
    cmds:
      - .venv/bin/python data-source-ingester/load_to_bq.py

  dbt-bin:
    desc: Run dbt `task dbt-bin -- compile`
    cmds:
      - pushd ./transformation_dbt && ../.venv/bin/dbt {{ .CLI_ARGS }} && popd
