name: 'transformation_dbt'
version: '1.0.0'
config-version: 2

profile: 'transformation_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  transformation_dbt:
    staging:
      +schema: wju_staging

    intermediate:
      +schema: wju_intermediate

    marts:
      +schema: wju_marts
